<a href="https://colab.research.google.com/github/Ilhami-Ramadhan/Projek-DAA/blob/main/LatihanDAA_Pertemuan03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
aList = ["Jhon", 33, "Toronto", True]
print(aList)

['Jhon', 33, 'Toronto', True]


In [21]:
import datetime as dt
tanggal = dt.date.today()

mahasiswa = ["Rama", "2023071075", "INF", "DAA", str(tanggal), "UPJ"]
print(mahasiswa)

['Rama', '2023071075', 'INF', 'DAA', '2024-09-20', 'UPJ']


In [7]:
print (aList[2])

Toronto


In [8]:
print(mahasiswa[0])

Rama


In [12]:
mahasiswa[0:3]

['Rama', '2023071075', 'INF']

In [13]:
print("nama kampus :", mahasiswa[5])

nama kampus : UPJ


In [15]:
warna=["merah","kuning","hijau","biru"]
print(warna[0:3])

['merah', 'kuning', 'hijau']


In [19]:
Warna=["merah","kuning","hijau","biru"]
for aWarna in Warna:
  print(aWarna + " Square")

merah Square
kuning Square
hijau Square
biru Square


In [26]:
for aMahasiswa in mahasiswa:
  print(aMahasiswa + " UPJ")

Rama UPJ
2023071075 UPJ
INF UPJ
DAA UPJ
2024-09-20 UPJ
UPJ UPJ


In [29]:
UPJ = ("Universitas", "Pembangunan", "Jaya")
UPJ[2]

'Jaya'

In [34]:
import pandas as pd

# Membuat DataFrame dengan data mahasiswa
df = pd.DataFrame([
   [1, "INF", 50, 30, 20],
   [2, "SIF", 55, 30, 25],
   [3, "TEKSIP", 40, 30, 10]
])

# Mengubah nama kolom
df.columns = ["No", "Prodi", "Mahasiswa", "LakiLaki", "Perempuan"]

# Menampilkan DataFrame
print(df)


   No   Prodi  Mahasiswa  LakiLaki  Perempuan
0   1     INF         50        30         20
1   2     SIF         55        30         25
2   3  TEKSIP         40        30         10


In [35]:
nested_tuple = (100, (200, 400, 600), 300, (400, 800))

# Menampilkan tuple bersarang
print(nested_tuple)


(100, (200, 400, 600), 300, (400, 800))


In [37]:
bin_colors ={
    "manual_color": "Yellow",
    "approved_color": "Green",
    "refused_color": "Red"
}
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'Green', 'refused_color': 'Red'}


In [38]:
bin_colors["approved_color"]="purple"
print(bin_colors)

{'manual_color': 'Yellow', 'approved_color': 'purple', 'refused_color': 'Red'}


In [42]:
bin_colors.get("approved_color")

'purple'

In [43]:
Mahasiswa = {
    "Satrio": {
        "NIM": 2023071050,
        "Prodi": "Informatika",
        "Universitas": "Universitas Pembangunan Jaya"
    },
    "Rais": {
        "NIM": 2023071049,
        "Prodi": "Informatika",
        "Universitas": "Universitas Pembangunan Jaya"
    },
    "Rama": {
        "NIM": 2023071048,
        "Prodi": "Informatika",
        "Universitas": "Universitas Pembangunan Jaya"
    },
    "Dimas": {
        "NIM": 2023071047,
        "Prodi": "Informatika",
        "Universitas": "Universitas Pembangunan Jaya"
    },
    "Fadil": {
        "NIM": 2023071046,
        "Prodi": "Informatika",
        "Universitas": "Universitas Pembangunan Jaya"
    },
}
# jika hanya ingin manggil satu
nama_mahasiswa = "Satrio"
info = Mahasiswa[nama_mahasiswa]
print(f"Nama: {nama_mahasiswa}, NIM: {info['NIM']}, Prodi: {info['Prodi']}, Universitas: {info['Universitas']}")


Nama: Satrio, NIM: 2023071050, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya


In [45]:
for nama, info in Mahasiswa.items():
    print(f"Nama: {nama}, NIM: {info['NIM']}, Prodi: {info['Prodi']}, Universitas: {info['Universitas']}")



Nama: Satrio, NIM: 2023071050, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya
Nama: Rais, NIM: 2023071049, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya
Nama: Rama, NIM: 2023071048, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya
Nama: Dimas, NIM: 2023071047, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya
Nama: Fadil, NIM: 2023071046, Prodi: Informatika, Universitas: Universitas Pembangunan Jaya


In [46]:
def pisahkan_warna(kata_kata):


  warna_kata = {'yellow': set(), 'red': set()}
  warna_dominan = {'yellow': {'dandelions', 'leaves'}, 'red': {'blood', 'rose', 'fire hydrant'}}

  for kata in kata_kata:
    for warna in warna_dominan:
      if kata in warna_dominan[warna]:
        warna_kata[warna].add(kata)

  return warna_kata

kata_kata = {'blood', 'rose', 'dandelions', 'fire hydrant', 'leaves'}
hasil = pisahkan_warna(kata_kata)
print(hasil)

{'yellow': {'dandelions', 'leaves'}, 'red': {'fire hydrant', 'rose', 'blood'}}


In [49]:
import numpy as np

Matrix = np.array([[100, 200, 300], [700, 600, 500], [900, 1000, 800]])
print(Matrix)



[[ 100  200  300]
 [ 700  600  500]
 [ 900 1000  800]]
